# Generated by Django 3.2.7 on 2021-09-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livedata', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='period',
        ),
        migrations.AlterModelOptions(
            name='weather_data',
            options={'verbose_name_plural': 'cities'},
        ),
    ]
