# Generated by Django 3.2.7 on 2021-10-10 19:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('livedata', '0008_auto_20211009_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='period',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('labels', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='weather_data_chart',
        ),
        migrations.AlterField(
            model_name='weather_data',
            name='Timestamp',
            field=models.IntegerField(),
        ),
    ]
