# Generated by Django 3.2.7 on 2021-10-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livedata', '0009_auto_20211011_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='period',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='weather_data',
            name='Temperature',
            field=models.FloatField(max_length=50),
        ),
    ]
