# Generated by Django 3.2.7 on 2021-10-20 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livedata', '0014_alter_period_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='labels',
        ),
    ]
