# Generated by Django 3.2.7 on 2021-10-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livedata', '0015_remove_period_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='labels',
            field=models.IntegerField(default=True),
        ),
    ]
