# Generated by Django 3.2.7 on 2021-10-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livedata', '0016_period_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='labels',
            field=models.CharField(max_length=100),
        ),
    ]
